using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Security.Cryptography;
using System.Text;
using Deukyeonglee.HierarchyTags.Contracts;
using UnityEditor;

namespace Deukyeonglee.HierarchyTags.Editor.Infrastructure
{
    internal static class HierarchyTagRedirectCodeGenerator
    {
        internal const string OutputDirectory = "Assets/HierarchyTags.Generated";
        internal const string SourcePath = OutputDirectory + "/HierarchyTagRedirects.g.cs";
        private const string AssemblyReferencePath = OutputDirectory + "/HierarchyTags.Generated.asmref";
        private const string AssemblyReference =
            "{\n    \"reference\": \"GUID:1733f85150e02e2458653167e0e0638a\"\n}\n";

        internal static string GenerateIfChanged(ITagCatalog catalog, IReadOnlyList<TagRedirect> redirects)
        {
            string code = BuildSource(catalog, redirects, out string revision);
            string projectRoot = Path.GetFullPath(Path.Combine(UnityEngine.Application.dataPath, ".."));

            // 생성물은 프로젝트가 소유합니다. Registry/Git/Local 패키지의 설치 경로에 쓰지 않습니다.
            bool changed = WriteIfChanged(Path.Combine(projectRoot, AssemblyReferencePath), AssemblyReference);
            changed |= WriteIfChanged(Path.Combine(projectRoot, SourcePath), code);
            if (changed)
            {
                AssetDatabase.Refresh();
            }

            return revision;
        }

        internal static string BuildSource(
            ITagCatalog catalog,
            IReadOnlyList<TagRedirect> redirects,
            out string revision)
        {
            if (catalog == null)
            {
                throw new ArgumentNullException(nameof(catalog));
            }

            if (redirects == null)
            {
                throw new ArgumentNullException(nameof(redirects));
            }

            var mappings = new SortedDictionary<string, string>(StringComparer.OrdinalIgnoreCase);
            foreach (TagRedirect redirect in redirects)
            {
                if (!catalog.TryResolve(redirect.OldTag.Value, out TagId target))
                {
                    throw new InvalidOperationException("Redirect 대상을 해석할 수 없습니다: " + redirect.OldTag.Value);
                }

                mappings[redirect.OldTag.Value] = target.Value;
            }

            var entries = new StringBuilder();
            foreach (KeyValuePair<string, string> pair in mappings)
            {
                entries.Append("            mappings.Add(");
                entries.Append(ToLiteral(pair.Key));
                entries.Append(", ");
                entries.Append(ToLiteral(pair.Value));
                entries.Append(");\n");
            }

            string entryText = entries.ToString();
            revision = ComputeRevision("HierarchyTagRedirects:v1\n" + entryText);

            return "// <auto-generated />\n" +
                "using System.Collections.Generic;\n\n" +
                "namespace Deukyeonglee.HierarchyTags\n" +
                "{\n" +
                "    internal static partial class HierarchyTagRedirects\n" +
                "    {\n" +
                "        static partial void PopulateTargets(Dictionary<string, string> mappings, ref string revision)\n" +
                "        {\n" +
                "            revision = \"" + revision + "\";\n" +
                entryText +
                "        }\n" +
                "    }\n" +
                "}\n";
        }

        private static bool WriteIfChanged(string path, string content)
        {
            if (File.Exists(path) && string.Equals(File.ReadAllText(path), content, StringComparison.Ordinal))
            {
                return false;
            }

            Directory.CreateDirectory(Path.GetDirectoryName(path));
            File.WriteAllText(path, content, new UTF8Encoding(false));
            return true;
        }

        private static string ComputeRevision(string value)
        {
            using SHA256 sha = SHA256.Create();
            return BitConverter.ToString(sha.ComputeHash(Encoding.UTF8.GetBytes(value))).Replace("-", "");
        }

        private static string ToLiteral(string value)
        {
            var result = new StringBuilder("\"");
            foreach (char character in value)
            {
                result.Append("\\u");
                result.Append(((int)character).ToString("X4", CultureInfo.InvariantCulture));
            }

            result.Append('"');
            return result.ToString();
        }
    }
}
